steps:
  - name: gcr.io/cloud-builders/docker
    args:
      ["build", "-t", "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${SHORT_SHA}", "products-app/"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/${_SERVICE_NAME}"]

  - name: "gcr.io/products-app-aw/helm:3.2.0"
    args:
      [
        "install",
        "${_HELM_RELEASE_NAME}", 
        "helm/products-app", 
        "--create-namespace", 
        "--namespace", 
        "${_NAMESPACE}",
        "--set",
        "image.tag=${SHORT_SHA}"
      ]
