steps:
  - name: gcr.io/cloud-builders/go
    args:
      ["build", "-t", "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${SHORT_SHA}", "app/"]
  - name: gcr.io/cloud-builders/docker
    args:
      ["build", "-t", "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${SHORT_SHA}", "app/"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/${_SERVICE_NAME}"]

  - name: "gcr.io/products-app-aw/helm:3.2.0"
    env:
    - 'CLOUDSDK_COMPUTE_REGION=${_CLUSTER_REGION}'
    - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'
    args:
      [
        "upgrade",
        "${_HELM_RELEASE_NAME}", 
        "helm/products-app", 
        "--namespace", 
        "${_NAMESPACE}",
        "--set",
        "image.tag=${SHORT_SHA}"
      ]

  - name: "gcr.io/products-app-aw/helm:3.2.0"
    env:
    - 'CLOUDSDK_COMPUTE_REGION=${_CLUSTER_REGION}'
    - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'
    args:
      [
        "get",
        "values",
        "${_HELM_RELEASE_NAME}", 
        "--namespace", 
        "${_NAMESPACE}"
      ]
